security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Participant
                property: pseudo
    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: listSorties

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 #30 days en secondes

            #logout_on_user_chlange: true
            logout:
                path: logout
                target: /
    encoders:
        App\Entity\Participant:
            algorithm: bcrypt

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }