security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Participant
                property: pseudo
    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            #logout_on_user_change: true
            logout:
                path: logout
                target: accueil
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }